### ISSUE TITLE
Dissable network debug info?

### ISSUE THREAD

**Issue by zeronobody0** [rameshvarun/netplayjs#83]
I'm trying to make a game using this library and it seems like there is an always-on debug info box. Is there any way to disable it?

**Comment by hchiam** [comment]
i'd like an option for this too. otherwise i have to do this: 
```css
canvas + div {
  display: none !important;
}
```
